# Generated by Django 3.0.5 on 2024-05-29 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauthentication', '0002_auto_20240529_1243'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='user_db',
        ),
    ]
