# Generated by Django 3.0.5 on 2024-05-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauthentication', '0003_auto_20240529_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_db',
            name='confirm_password',
            field=models.CharField(max_length=128),
        ),
    ]
