# Generated by Django 3.0.5 on 2024-04-11 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_image',
        ),
    ]
