# Generated by Django 3.0.5 on 2024-04-14 17:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mygallary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpost',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
