# Generated by Django 3.0.5 on 2024-06-01 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mygallary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
