# Generated by Django 3.0.5 on 2024-05-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygallary', '0002_newpost_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='caption',
            field=models.CharField(max_length=30),
        ),
    ]
