# Generated by Django 3.0.5 on 2024-05-31 11:29

from django.db import migrations, models
import django.db.models.deletion
import mygallary.models


class Migration(migrations.Migration):

    dependencies = [
        ('userauthentication', '0004_auto_20240529_2302'),
        ('mygallary', '0004_newpost_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='user',
            field=models.ForeignKey(default=mygallary.models.newpost.get_default_user, on_delete=django.db.models.deletion.CASCADE, to='userauthentication.user_db'),
        ),
    ]
